version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_bin, --init-connect='SET NAMES utf8mb4;']

  xray-daemon:
    build:
      context: .
      dockerfile: Dockerfile.xray
    env_file:
      - xray.env

  app:
    image: aws-xray-example-play-scalikejdbc:0.0.1
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DB_NAME: example_aws_xray_play
      SERVER_PORT: 9000
      AWS_XRAY_DAEMON_ADDRESS: xray-daemon:2000
      AWS_XRAY_TRACING_NAME: aws-xray-example-play-scalikejdbc
      NT_AWS_XRAY_CAPTURE_QUERY: "on"
    depends_on:
      - db
      - xray-daemon
